# -*- coding: utf-8 -*-
"""DQN-Restless bandit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EPz6lk6OJFLgbmd2MD-3CfI7kSTICG3Y
"""

import numpy as np
import random
import torch
import torch.nn as nn
import torch.optim as optim
from collections import deque
import matplotlib.pyplot as plt

# Define the restless bandit environment
class RestlessBanditEnv:
    def __init__(self, n_arms=10, context_size=3):
        self.n_arms = n_arms
        self.context_size = context_size
        self.state = np.random.randn(n_arms, context_size)
        self.time_step = 0

    def reset(self):
        self.state = np.random.randn(self.n_arms, self.context_size)
        self.time_step = 0
        return self.state

    def step(self, action):
        reward = self.state[action].sum() + np.random.randn() * 0.1  # Reward based on context + noise
        self.time_step += 1

        # State evolves regardless of action (restless bandit)
        self.state = self.state + np.random.randn(self.n_arms, self.context_size) * 0.05

        return self.state, reward, self.time_step >= 100  # Simulation for 100 steps

# Define a simple neural network for DQN
class DQNetwork(nn.Module):
    def __init__(self, state_size, action_size):
        super(DQNetwork, self).__init__()
        self.fc1 = nn.Linear(state_size, 128)
        self.fc2 = nn.Linear(128, 64)
        self.fc3 = nn.Linear(64, action_size)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        return self.fc3(x)

# DQN agent
class DQNAgent:
    def __init__(self, state_size, action_size):
        self.state_size = state_size
        self.action_size = action_size
        self.memory = deque(maxlen=2000)
        self.gamma = 0.99    # Discount factor
        self.epsilon = 1.0   # Exploration rate
        self.epsilon_min = 0.01
        self.epsilon_decay = 0.995
        self.learning_rate = 0.001
        self.model = DQNetwork(state_size, action_size)
        self.optimizer = optim.Adam(self.model.parameters(), lr=self.learning_rate)
        self.criterion = nn.MSELoss()

    def remember(self, state, action, reward, next_state, done):
        self.memory.append((state, action, reward, next_state, done))

    def act(self, state):
        if np.random.rand() <= self.epsilon:
            return random.randrange(self.action_size)
        state = torch.FloatTensor(state)
        q_values = self.model(state).detach().numpy()
        return np.argmax(q_values)

    def replay(self, batch_size):
        minibatch = random.sample(self.memory, batch_size)
        for state, action, reward, next_state, done in minibatch:
            state = torch.FloatTensor(state)
            next_state = torch.FloatTensor(next_state)
            target = reward
            if not done:
                target += self.gamma * np.amax(self.model(next_state).detach().numpy())
            target_f = self.model(state).detach().numpy()
            target_f[action] = target
            target_f = torch.FloatTensor(target_f)
            self.optimizer.zero_grad()
            output = self.model(state)
            loss = self.criterion(output, target_f)
            loss.backward()
            self.optimizer.step()

        if self.epsilon > self.epsilon_min:
            self.epsilon *= self.epsilon_decay

# Training the agent in the restless bandit environment
if __name__ == "__main__":
    env = RestlessBanditEnv()
    state_size = env.context_size * env.n_arms
    action_size = env.n_arms
    agent = DQNAgent(state_size, action_size)

    episodes = 100
    batch_size = 5

    # Track rewards for plotting
    rewards_list = []
    action_counts = np.zeros(env.n_arms)

    for e in range(episodes):
        state = env.reset().flatten()
        total_reward = 0
        for time in range(100):  # Limit the number of steps per episode
            action = agent.act(state)
            next_state, reward, done = env.step(action)
            next_state = next_state.flatten()
            agent.remember(state, action, reward, next_state, done)
            state = next_state
            total_reward += reward
            action_counts[action] += 1  # Track action selection
            if done:
                break
            if len(agent.memory) > batch_size:
                agent.replay(batch_size)
        rewards_list.append(total_reward)  # Store total reward for the episode
        print(f"Episode {e+1}/{episodes}, Total Reward: {total_reward}, Epsilon: {agent.epsilon:.2}")

    print("Training complete.")

    # Plot total rewards over episodes
    plt.figure(figsize=(12, 6))
    plt.subplot(3, 1, 1)
    plt.plot(rewards_list)
    plt.xlabel('Episodes')
    plt.ylabel('Total Reward')
    plt.title('DQN Performance on Restless Bandit Problem')

    # Plot action selection distribution
    plt.subplot(3, 1, 2)
    plt.bar(range(env.n_arms), action_counts)
    plt.xlabel('Arms (Actions)')
    plt.ylabel('Selection Count')
    plt.title('Action Selection Distribution')

    # Compute and plot cumulative rewards
    cumulative_rewards = np.cumsum(rewards_list)
    plt.subplot(3, 1, 3)
    plt.plot(cumulative_rewards)
    plt.xlabel('Episodes')
    plt.ylabel('Cumulative Reward')
    plt.title('Cumulative Reward Over Episodes')

    plt.tight_layout()
    plt.show()